
#  █░█ █ █▀▀ █░█   █▀█ █░█ ▄▀█ █░░ █ ▀█▀ █▄█   █▀▄▀█ █▀█ █▄▄ █▀▀ █▀█ █ █▄░█ █▀   █▀█ █░░ █░█ █▀▀ █ █▄░█
#  █▀█ █ █▄█ █▀█   ▀▀█ █▄█ █▀█ █▄▄ █ ░█░ ░█░   █░▀░█ █▄█ █▄█ █▄▄ █▄█ █ █░▀█ ▄█   █▀▀ █▄▄ █▄█ █▄█ █ █░▀█
#  By TMDevelopment | devtm.net | discord.devtm.net |

enable_debug: false

allow_bstats: true

select_locale: en.yml

hook_into_stacker: false

main_command_aliases:
  - "tmmobcoins"
  - "mc"

storage_type:
  # This will make the mobcoins read slowly, it VERY usefully/necessary for not make reads to the database if this is set to 0 will lag out the server
  read_delay: 5
  # Choose (file|database|sqlite) read more here: https://mobcoins.devtm.net/basic-setup/connecting-to-a-database
  type: file
  # Database drivers available only for database storage type
  driver: MySql
  connection:
    host: "localhost"
    port: "3306"
    database: "test"
    username: "root"
    password: ""
    table: "tmmobcoins"

first_join_give_mobcoins: 0

shop:
  # Read more here: https://mobcoins.devtm.net/basic-setup/making-the-shop
  # Every change in the setting will require a restart or reload (Plugman should work fine)
  settings:
    # This could use the mobcoins base command (ex: /mobcoins) to open the shop
    open_command: "mobcoinshop"
    shop_type: normal
  enabled: false
