
#     _____         _      _____         _ _ _          _____     _           _                _         _
#    | __  |___ ___| |_   |     |_ _ ___| |_| |_ _ _   |     |___| |_ ___ ___|_|___ ___    ___| |_ _ ___|_|___
#    | __ -| -_|_ -|  _|  |  |  | | | .'| | |  _| | |  | | | | . | . |  _| . | |   |_ -|  | . | | | | . | |   |
#    |_____|___|___|_|    |__  _|___|__,|_|_|_| |_  |  |_|_|_|___|___|___|___|_|_|_|___|  |  _|_|___|_  |_|_|_|
#                            |__|               |___|                                     |_|       |___|
# _____________________________________________________________________| Flares.dev | discord.flares.dev

enable_debug: false

allow_bstats: true

select_locale: en.yml

storage:
  # This is used to not spam the connection with a lot of reads, but if you want to disable this feature set the cache_time to 0
  cache_time: 5
  # Choose (file|mysql|sqlite)
  type: file
  # Database drivers available only for database storage type
  driver: MySql
  mysql:
    host: "localhost"
    port: 3306
    database: "test"
    username: "root"
    password: ""
    table: "flaretokens"

first_join_give_mobcoins: 0

rotating_shop_time_format: "%min% min %sec% sec"

physical_coin:
  enable: false
  only_the_killer_can_collect: true
  item:
    material: "[HEAD] eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTVmZDY3ZDU2ZmZjNTNmYjM2MGExNzg3OWQ5YjUzMzhkNzMzMmQ4ZjEyOTQ5MWE1ZTE3ZThkNmU4YWVhNmMzYSJ9fX0="
    display_name: "Physical Coin"

shop:
  # Rather if you want to have the shop enabled.
  enable: true
  # This could use the mobcoins base command (ex: /mobcoins) to open the shop.
  open_command: "mobcoinshop"
  # Add the shop file name (Example for "shop.yml" just shop). (Shops are added in the shop folder)
  main_shop: main