name: FlareMobcoins
version: ALPHA-3.0
main: net.devtm.tmmobcoins.TMMobCoinsPlugin
author: FlaresDevelopment
description: Best Mob coins plugin plugin
website: "https://flares.dev"
api-version: 1.13
commands:
  mobcoins:
    description: "This is the main command of FlareMobcoins"
    aliases:
      - tmmobcoins
      - mobcoin
      - flaremobcoins