name: FlareMobcoins
version: 3.0
main: net.flares.flaremobcoins.MobcoinsByFlares
author: FlaresDevelopment
description: A mobcoins plugin made with love in Romania.
website: "https://flares.dev"
api-version: 1.13
commands:
  mobcoins:
    description: "This is the main command of FlareMobcoins"
    aliases:
      - tmmobcoins
      - mobcoin
      - mobcoins
      - mcoins
      - flaremobcoins